### ISSUE TITLE
Problem with Debian based systems 

### ISSUE THREAD

**Issue by animal811** [arevindh/pihole-speedtest#126]
Hello and thank you for your mod

I would like to get this mod to work on Lubuntu or other debian  based systems but i had some problems using the install instructions.

i have managed to get the GUI working and when i run the speedtest cli, it works ! 

i am having problems Inserting the data into the sql database, i have minimal knowledge on making a db file on SQL lite so i thought it best to raise a support issue for this.

**Comment by SHelfinger** [comment]
Hello,

I'm just guessing here since the information is really limited.

With GUI you mean the pihole-website (With mod speedtest installed)?

Problems with inserting data to SQLite3... Have you executed the command?

`cp /var/www/html/admin/scripts/pi-hole/speedtest/speedtest.db /etc/pihole/`

This command copies the speedtest database to the pihole configuration folder (Important to insert the speedtest result).

Cheers
