### ISSUE TITLE
Speedtest values are strange in the UI.

### ISSUE THREAD

**Issue by abacao** [arevindh/pihole-speedtest#13]
Hello,

My values in the webui are quite strange and much different than in the CLI.

Is that a bug in the latest version with the latest pihole version?

I'm running these versions:
Pi-hole Version v4.2.1 Web Interface Version v4.1.2 (Update available!) FTL Version v4.2.1

**Comment by arevindh** [comment]
Can you provide some screenshots

**Comment by abacao** [comment]
https://imgur.com/a/pkOxU2L

All are automatic besides the 2 at the top.

The ones that underlined were run in the machine with this command

> $ sudo bash /var/www/html/admin/scripts/pi-hole/speedtest/speedtest.sh

**Comment by arevindh** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the latest stable version and then please use the [this link](https://github.com/arevindh/pihole-speedtest/issues/new)
